### ISSUE TITLE
Can't find field [pngSticker] with signature [Lorg/drinkless/tdlib/TdApi$InputFile;]

### ISSUE THREAD

**Issue by Teramaks** [tdlib/td#1050]
Im coding on Java, using IntelliJ IDEA 2020, OS Ubuntu 20
Firstly I started writing project on Windows 7 and now need test it on Linux? but I have erro message on library load like this:

[ 1][t 0][1589554042.159195185][tl_jni_object.cpp:37]	Can't find field [pngSticker] with signature [Lorg/drinkless/tdlib/TdApi$InputFile;]
FATAL ERROR in native method: Can't find field [pngSticker] with signature [Lorg/drinkless/tdlib/TdApi$InputFile;]
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	- locked <0x00000000c90d55c0> (a java.util.Vector)
	- locked <0x00000000c9268388> (a java.util.Vector)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:809)
	- locked <0x00000000c86bfd00> (a java.lang.Runtime)
	at java.lang.System.load(System.java:1088)
	at com.tailer.Application.main(Application.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

`try {
      System.load("/home/teramaks/IdeaProjects/telegram-cloud/tdlib/bin/libtdjni.so");
//      System.load("C:/Users/Teramaks/Desktop/telegram-cloud/tdlib/tdjni.dll");
    } catch (UnsatisfiedLinkError e) {
      e.printStackTrace();
    }`

But when I create new project and run example all works fine

**Comment by levlam** [comment]
You have different version of tdjni.dll and generated Java classes. Generated Java classes are newer.
