### ISSUE TITLE
FFI fails to load tdjson.dll which was built for NodeJS (Windows) when it is run from Cmd

### ISSUE THREAD

**Issue by AlexBlade** [tdlib/td#1081]
Hello, Dear Developers!

I built TDLib according to official instruction to use it from JavaScript (TypeScript). I selected JavaScript as a language, Windows (node.js) as an environment then I chose x64 as a bitness and used PowerShell to perform building process. The library was built successfully and I started my tries to work with it.

I used Airgram to make a client and try to connect and get some data. At this moment I encountered with problem. When I executed my program from Windows command line I got error: `Error: "Dynamic Linking Error: Win32 error 126"`. But when I tried to run this program from Bash (from MinGW64) then program was executed correctly and gave me no errors about .dll loading problems.

At those moment I decided that ffi-napi which is used by Airgram, has some errors or troubles. Then I made a little program to check library loading using ffi-napi. The code is placed below:

```
import ffi from 'ffi-napi';

class FfiTester {
    static test() {
        const arg1 = process.argv.find(arg => ~arg.indexOf('--lib'));
        const libPath = arg1.split('=')[1];
        const arg2 = process.argv.find(arg => ~arg.indexOf('--func'));
        const funcName = arg2.split('=')[1];
        console.log('Path: ' + libPath);
        const lib = ffi.DynamicLibrary(libPath, 0)
        const buf = lib.get(funcName);
        console.log(buf);
        lib.close();
    }
}

FfiTester.test();
```

The program is executed used next command:

`node index.js --lib=tdjson.dll --func=td_json_client_send`

Executing the program from bash gave the result below:

```
$ node ./index.js --lib=tdjson.dll --func=td_json_client_send
(node:12336) ExperimentalWarning: The ESM module loader is experimental.
Path: tdjson.dll
<Buffer@0x00007FFDC9D61EF0 type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set]
, name: 'void', ffi_type: <Buffer@0x00007FFDFBAB18D0 name: 'void'> }, name: 'td_json_client_send'>
```
So, that's ok. But making the same from command line gave me the error below: 

```
C:\Development\Projects\VsCode\ffi>node ./index.js --lib=tdjson.dll --func=td_json_client_send
(node:12604) ExperimentalWarning: The ESM module loader is experimental.
Path: tdjson.dll
C:\Development\Projects\VsCode\ffi\node_modules\ffi-napi\lib\dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err);
          ^

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (C:\Development\Projects\VsCode\ffi\node_modules\ffi-napi\lib\dynamic_library.js:74:11)
    at Object.DynamicLibrary (C:\Development\Projects\VsCode\ffi\node_modules\ffi-napi\lib\dynamic_library.js:33:12)
    at Function.test (file:///C:/Development/Projects/VsCode/ffi/index.js:10:25)
    at file:///C:/Development/Projects/VsCode/ffi/index.js:17:11
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```
For the purity of the experiment I decided to use shell32.dll and check if the problem will appear. And voila: 

```
C:\Development\Projects\VsCode\ffi>node ./index.js --lib=shell32.dll --func=DllGetVersion
(node:4984) ExperimentalWarning: The ESM module loader is experimental.
Path: shell32.dll
<Buffer@0x00007FFE1158B960 type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void', ffi_type: <Buffer@0x00007FFDFD3818D0 name: 'void'> }, name: 'DllGetVersion'>
```
No problem! ffi-napi works correctly. Therefore, either there is a problem with running program that uses TDLib from Windows command line, or I'm doing something wrong. 

Please, guys, help.

**Comment by AlexBlade** [comment]
Sorry for disturbing, guys. I found the reason of the error related to `Error: "Dynamic Linking Error: Win32 error 126"`.

After compilation we need to place also all dependencies DLLs either to folder on system path (system32 for example) or near the tdjson.dll.

In my case there were next libraries:
```
zlib1.dll
libcrypto-1_1-x64.dll
libssl-1_1-x64.dll
```

They were placed to `vcpkg\installed\x64-windows\bin` in the folder that contains sources during building process..

I would like to ask maintainers of the TDLib-project to add this information for future usage to official guide.
