### ISSUE TITLE
Can't find field [thumbnail] with signature [Lorg/drinkless/tdlib/TdApi$PhotoSize;]

### ISSUE THREAD

**Issue by hossein1113** [tdlib/td#1171]
[ 1][t 0][1597550474.528701305][tl_jni_object.cpp:37]	Can't find field [thumbnail] with signature [Lorg/drinkless/tdlib/TdApi$PhotoSize;]
FATAL ERROR in native method: Can't find field [thumbnail] with signature [Lorg/drinkless/tdlib/TdApi$PhotoSize;]
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	- locked <0x00000007809068b0> (a java.util.Vector)
	- locked <0x000000078095c110> (a java.util.Vector)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	- locked <0x000000078090e340> (a java.lang.Runtime)
	at java.lang.System.loadLibrary(System.java:1122)
	at sample.Controller.<clinit>(Controller.java:126)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:927)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
	at sample.Testmsg.start(Testmsg.java:41)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.LauncherImpl$$Lambda$55/1274001399.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/1031980531.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$50/1663891755.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/1642534850.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186)
	at com.sun.glass.ui.win.WinApplication$$Lambda$38/1942406066.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
get this error to run java example in intellij. windows 10 64 .
please help?

**Comment by levlam** [comment]
You have built TDLIb shared library and Java classes of different versions.

**Comment by hossein1113** [comment]
thanks.
