### ISSUE TITLE
Exported jar can only run on project development machine

### ISSUE THREAD

**Issue by eos1d3** [tdlib/td#1256]
Machine is running Windows 10, tested with Java JDK 14 and 8, using latest commit, complied with 64-bit version with the Example.java. It runs well on Eclipse as well as exported jar at command prompt.

Then I copy the exact project folder to other two Windows 10 machine, It never works. The error messages are:

```
java.lang.UnsatisfiedLinkError: D:\Applications\tdlib-services3\tdjni.dll: There are no more files
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.drinkless.tdlib.example.Example.<clinit>(Example.java:59)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:59)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.UnsatisfiedLinkError: org.drinkless.tdlib.Client.nativeClientExecute(Lorg/drinkless/tdlib/TdApi$Function;)Lorg/drinkless/tdlib/TdApi$Object;
        at org.drinkless.tdlib.Client.nativeClientExecute(Native Method)
        at org.drinkless.tdlib.Client.execute(Client.java:83)
        at org.drinkless.tdlib.example.Example.main(Example.java:310)
        ... 5 more
```

The major files in the folder contains:
```
libcrypto-1_1-x64.dll
libssl-1_1-x64.dll
tdjni.dll
tdjni.lib
tdlib\
main.jar
zlib1.dll
```

The only different is the project development machine has been used to build the TDLib.
I have tried to remove almost all environment variables and it still runs on this machine.

So what is missing in other machines?

Thanks!

**Comment by levlam** [comment]
You may need to install Visual c++ redistributable package on the target machine.

**Comment by eos1d3** [comment]
Thanks! The problem solved.
