### ISSUE TITLE
JAVA: Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long com.tdlibclient.Client.createNativeClient()'

### ISSUE THREAD

**Issue by rsibweza** [tdlib/td#1412]
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long com.tdlibclient.Client.createNativeClient()'
	at com.tdlibclient.Client.createNativeClient(Native Method)
	at com.tdlibclient.Client.<init>(Client.java:52)
	at com.tdlibclient.Client.main(Client.java:198)

The dll is working but this is the final step where i am stuck. How can i make the Nativeclient work in JAva

**Comment by levlam** [comment]
You have a wrong DLL. Likely, you have the DLL and Java classes from different TDLib versions.
