### ISSUE TITLE
Ubuntu 18.04 Java example launch returns UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#1720]
Hi, I've built (following the instructions here: https://tdlib.github.io/td/build.html?language=Java with clang option) tdlib from master, now trying to launch at my ubuntu 18.04, getting the following error:

`java.lang.UnsatisfiedLinkError: undefined symbol: _ZNKSt3__119__shared_weak_count13__get_deleterERKSt9type_info
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2659)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.drinkless.tdlib.example.Example.<clinit>(Example.java:59)
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'org.drinkless.tdlib.TdApi$Object org.drinkless.tdlib.Client.nativeClientExecute(org.drinkless.tdlib.TdApi$Function)'
        at org.drinkless.tdlib.Client.nativeClientExecute(Native Method)
        at org.drinkless.tdlib.Client.execute(Client.java:83)
        at org.drinkless.tdlib.example.Example.main(Example.java:302)`

Could you please suggest how to solve that?

**Comment by Mike497** [comment]
Well.. I've rebuilt everything from clean slate with g++ and run example from /td/tdlib/bin - all works fine.
