### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no tdjni in java.library.path:

### ISSUE THREAD

**Issue by Ioakeimis** [tdlib/td#2358]
I successfully managed to execute all the commands mentioned in the build instructor generator for JAVA on Apple silicon. When I try to just run the main method in the Example.java class I get the following error:

java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: /Users/username/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
	at java.base/java.lang.System.loadLibrary(System.java:2047)
	at org.drinkless.tdlib.Client.<clinit>(Client.java:18)
	at org.drinkless.tdlib.example.Example.main(Example.java:302)
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.drinkless.tdlib.Client.nativeClientSetLogMessageHandler(int, org.drinkless.tdlib.Client$LogMessageHandler)'
	at org.drinkless.tdlib.Client.nativeClientSetLogMessageHandler(Native Method)
	at org.drinkless.tdlib.Client.setLogMessageHandler(Client.java:139)
	at org.drinkless.tdlib.example.Example.main(Example.java:302)

There was another issue in the closed issues section that had the same error but I was unable to benefit from it in any way :(

**Comment by levlam** [comment]
You need to specify `java.library.path` to JVM, For example, `java '-Djava.library.path=.' org/drinkless/tdlib/example/Example`.

**Comment by Ioakeim** [comment]
Where do I do this? I am using IntelliJ as an IDE

**Comment by levlam** [comment]
https://stackoverflow.com/questions/19308010/how-to-set-the-java-library-path-in-intellij-idea

**Comment by Ioakeimis** [comment]
I included what you have written in the VM Options.
Now I get a new error:

Error: Could not find or load main class java
Caused by: java.lang.ClassNotFoundException: java

But I don't get it. I have included the Example class as a main class in the edit configurations. (refer to attachment below)

![Screenshot 2023-03-19 at 21 33 34](https://user-images.githubusercontent.com/99436465/226207414-17de1b75-3d72-4f90-8159-0ac56f42b2bf.png)

**Comment by Valentyna12** [comment]
???

сб, 18 мар. 2023 г., 21:43 Aliaksei Levin ***@***.***>:

**Comment by sizov2405** [comment]
Aliaksei, I cloned the project, built it for Mac/Apple silicon following the instruction, then I imported the project to the Intellij and added a VM argument -Djava.library.path=. but I still get:

java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: .
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.drinkless.tdlib.Client.<clinit>(Client.java:18)
	at org.drinkless.tdlib.example.Example.main(Example.java:301)

**Comment by levlam** [comment]
You need to specify path to tdjni.dylib as `java.library.path`. If you don't run the example from command-line, then "." is highly likely to be a wrong path.

**Comment by sizov2405** [comment]
> You need to specify path to tdjni.dylib as `java.library.path`. If you don't run the example from command-line, then "." is highly likely to be a wrong path.

It works! Thanks!
