### ISSUE TITLE
Error when running Example

### ISSUE THREAD

**Issue by dumbled00r** [tdlib/td#2473]
Well, I'm currently doing a Project related to TDLib, but I'm struggling to run Example
Whenever I run, I always encounter the error
```
java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: /Users/dumbled00r/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:880)
	at java.base/java.lang.System.loadLibrary(System.java:2051)
	at org.drinkless.tdlib.Client.<clinit>(Client.java:18)
	at org.example.App.main(App.java:303)
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.drinkless.tdlib.Client.nativeClientSetLogMessageHandler(int, org.drinkless.tdlib.Client$LogMessageHandler)'
	at org.drinkless.tdlib.Client.nativeClientSetLogMessageHandler(Native Method)
	at org.drinkless.tdlib.Client.setLogMessageHandler(Client.java:139)
	at org.example.App.main(App.java:303)
	
```

Please help me out!. I use both Windows and Mac OS (Apple Silicon), but both of them have this same error

**Comment by levlam** [comment]
You didn't specify `java.library.path` or built `tdjni` for a wrong architecture.
