### ISSUE TITLE
java.lang.UnsatisfiedLinkError: C:\Users\PC\td\tdlib\bin\tdjni.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by dumbled00r** [tdlib/td#2477]
I'm trying to run the example, i added VM arguments  -Djava.library.path="C:\Users\PC\td\tdlib\bin"
It doesn't work for me, it shows the error
```
java.lang.UnsatisfiedLinkError: C:\Users\PC\td\tdlib\bin\tdjni.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:251)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2437)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:880)
	at java.base/java.lang.System.loadLibrary(System.java:2051)
	at org.drinkless.tdlib.Client.<clinit>(Client.java:18)
	at org.drinkless.tdlib.example.Example.main(Example.java:302)
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.drinkless.tdlib.Client.nativeClientSetLogMessageHandler(int, org.drinkless.tdlib.Client$LogMessageHandler)'
	at org.drinkless.tdlib.Client.nativeClientSetLogMessageHandler(Native Method)
	at org.drinkless.tdlib.Client.setLogMessageHandler(Client.java:139)
	at org.drinkless.tdlib.example.Example.main(Example.java:302)

```

I've searched through my PC, I don't know where can I find the dependent libraries and copy it where/bin path, please help me out~

**Comment by aaalzya** [comment]
yes

**Comment by dumbled00r** [comment]
> yes

Do you have any solutions?

**Comment by levlam** [comment]
You need `libctypto`, `libssl` and `zlib` DLLs. Do you have them installed in the same directory "C:\Users\PC\td\tdlib\bin"?

**Comment by dumbled00r** [comment]
I installed it with https://tdlib.github.io/td/build.html, and it still exists in that directory

> You need `libctypto`, `libssl` and `zlib` DLLs. Do you have them installed in the same directory "C:\Users\PC\td\tdlib\bin"?

**Comment by aaalzya** [comment]
#967773852362

**Comment by aaalzya** [comment]
اليمن

**Comment by dumbled00r** [comment]
> #967773852362

What is this?

**Comment by levlam** [comment]
This is expected behavior of DLL loading. `java.library.path` can affect only DLLs explicitly loaded in Java source code. All their dependent DLLs must be automatically loaded by OS and hence they can be only found in standard paths, the directory from which the application loaded. and the current directory. See https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order for more details. Therefore, you need to copy all the libraries to the working directory of your project or to a directory available through path environment variable.

**Comment by dumbled00r** [comment]
I copied all .dll files in bin towards System32 directory, now it works!
