### ISSUE TITLE
Failed to load 'td_json_client_create': Symbol not found: node_register_module_v115

### ISSUE THREAD

**Issue by david-benes** [tdlib/td#2612]
I was able to compile tdlib on alpine 3.18 (node:20-alpine) in docker with the following basefile:

```
FROM node:20-alpine

RUN apk add --update
RUN apk add openssh-client
RUN apk add python3
RUN apk add build-base
RUN apk add libc6-compat
RUN apk add yarn
RUN yarn global add node-gyp

# Install tdlib
# https://github.com/wcsiu/tdlib/blob/master/alpine/Dockerfile
WORKDIR /

RUN apk add --no-cache \
        ca-certificates

RUN apk add --no-cache --virtual .build-deps \
        g++ \
        make \
        cmake \
        git \
        gperf \
        libressl-dev \
        zlib-dev \
        zlib-static \
        linux-headers;

RUN git clone https://github.com/tdlib/td.git && \
    cd td && \
    git checkout v1.8.0 && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    cmake --build . && \
    make install
```

However, when I attempt to create the client, I receive the following error:
Failed to load 'td_json_client_create': Symbol not found: node_register_module_v115

```
  const client = tdl.createClient({
    apiId: this.$config.telegram.api_id,
    apiHash: this.$config.telegram.api_hash,
    databaseDirectory: `${user_dir}/db`,
    filesDirectory: `${user_dir}/files`,
    useTestDc: true,
    verbosityLevel: 2
  })
```

Any idea what is causing it or how can I workaround this missing symbol?

**Comment by david-benes** [comment]
```
  "stack": "Error: Failed to load 'td_json_client_create': Symbol not found: node_register_module_v115
    at loadAddon (/var/apps/workers/node_modules/tdl/dist/addon.js:52:9)
    at init (/var/apps/workers/node_modules/tdl/dist/index.js:72:38)
```

**Comment by levlam** [comment]
This is an error from the `tdl` Node.js package, which means that the package was built under different Node.js version. Likely, you installed the package and then update Node.js. Try to delete the directory `/var/apps/workers/node_modules` and reinstall all packages.

**Comment by david-benes** [comment]
@levlam sadly, this is not the case. I created a repo to demonstrate the issue.
https://github.com/Jollor/tdl-alpine-build

I will close it here and open a new issue in tdl.
