### ISSUE TITLE
C# code works on win 10 but not work on win11 and win server 2022

### ISSUE THREAD

**Issue by isuruwe** [tdlib/td#2959]
Give this error in event viewer in win server 2022 and exit app but run on win 10

Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
at <Module>.td.ClientManager.execute(td.tl.unique_ptr<td::td_api::Object>*, td.tl.unique_ptr<td::td_api::Function>*)
at Telegram.Td.Client.Execute(Telegram.Td.Api.Function)
at ChannelWriter.Telegram.Agent+<OnDoWork>d__24.MoveNext()
at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[ChannelWriter.Telegram.Agent+<OnDoWork>d__24, ChannelWriter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<OnDoWork>d__24 ByRef)
at ChannelWriter.Telegram.Agent.OnDoWork(System.ComponentModel.DoWorkEventArgs)
at System.ComponentModel.BackgroundWorker.WorkerThreadStart(System.Object)
at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr, System.Object[], System.Object, System.Object[] ByRef)
at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessageSink)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by isuruwe** [comment]
issue was target pc not installed latest version of Microsoft Visual C++ Redistributable. latest version is 14.40.33810.0
