### ISSUE TITLE
TDLLib doesn't work in docker container

### ISSUE THREAD

**Issue by Jhon-Mosk** [tdlib/td#2981]
I'm trying run tdl client in container. And I get next error:
```
app-1  | [13:46:18 UTC] ERROR: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=musl node=20.15.1
app-1  |     loaded from: /usr/src/app/node_modules/tdl
app-1  | 
app-1  |     err: {
app-1  |       "type": "Error",
app-1  |       "message": "No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=musl node=20.15.1\n    loaded from: /usr/src/app/node_modules/tdl\n",
app-1  |       "stack":
app-1  |           Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=musl node=20.15.1
app-1  |               loaded from: /usr/src/app/node_modules/tdl
app-1  |           
app-1  |               at load.resolve.load.path (/usr/src/app/node_modules/node-gyp-build/node-gyp-build.js:60:9)
app-1  |               at load (/usr/src/app/node_modules/node-gyp-build/node-gyp-build.js:22:30)
app-1  |               at loadAddon (/usr/src/app/node_modules/tdl/dist/addon.js:14:43)
app-1  |               at init (/usr/src/app/node_modules/tdl/dist/index.js:78:38)
app-1  |               at Object.createClient (/usr/src/app/node_modules/tdl/dist/index.js:142:5)
app-1  |               at Object.createClient (/usr/src/app/lib/tdl/index.js:16:22)
app-1  |               at run (/usr/src/app/main.js:11:31)
app-1  |               at Object.<anonymous> (/usr/src/app/main.js:36:1)
app-1  |               at Module._compile (node:internal/modules/cjs/loader:1358:14)
app-1  |               at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
app-1  |     }
```
If I run this code without docker, just node, it's work perfect.

```
# Отчет о подробностях системы
---

## Подробности отчета
- **Дата создания:**                               2024-07-12 16:51:32

## Аппаратная информация:
- **Модель оборудования:**                         ASUSTeK COMPUTER INC. PRIME B250M-PLUS
- **Память:**                                      16,0 ГиБ
- **Процессор:**                                   Intel® Core™ i7-7700K × 8
- **Графика:**                                     NVIDIA GeForce GTX 1060 6GB
- **Ёмкость диска:**                               2,1 ТБ

## Программная информация:
- **Версия прошивки:**                             0808
- **Название ОС:**                                 Fedora Linux 40 (Workstation Edition)
- **Сборка ОС:**                                   (null)
- **Тип ОС:**                                      64-бит
- **Версия GNOME:**                                46
- **Оконный интерфейс:**                           X11
- **Версия ядра:**                                 Linux 6.9.7-200.fc40.x86_64
```

Docker version 27.0.3, build 7d4bcd8
Docker Compose version v2.27.0-desktop.2
local node  v20.15.1
node in docker v20.15.1-alpine

**Comment by Jhon-Mosk** [comment]
"tdl": "7.4.0"
tdlLib: 1.8.25

**Comment by levlam** [comment]
`tdl` doesn't provide prebuilt TDLib version for your OS in Docker. You need to build TDLib yourself for it.

**Comment by Jhon-Mosk** [comment]
I builded TDLib for Alpine and had this error.

**Comment by levlam** [comment]
`tdl` is unable to find the built TDLib.

**Comment by Jhon-Mosk** [comment]
Yes but he is there. Maybe version of TDLib build is 1.8.33 and version of tdl is 7.4.0. And they are not compatible.

**Comment by levlam** [comment]
They should be compatible, but this is better to be asked in the `tdl` repository.

**Comment by Jhon-Mosk** [comment]
I figured out what the problem was. You need to run the command ldd /path/to/file/libtdjson.so on the *.so file and it will be clear what is missing. It was necessary to install libc++-dev

**Comment by Scutua** [comment]
Please ^^

**Comment by Scutua** [comment]
Onething for mysafe i don't know much abou how to play telegram and the
option and quest to play. Also english to bad.

Maybe he come inside me and put the wrong wallet to me. Because i never see
assest. The one i recived it.

yesterday when i play telegram i see "de rov"and other around 4-5 with full
money stay in my telagram option each one 500 - 1000 million. I try to
click and delete they money and after that gone (run away out) and tell me
"thank you for full picture here , i get a lot from this more than nirmal
way"

I very angery abiut this and think how they can come in?:
1. I have bad set up
2. They know my pass
3.  Maybe my stupid click..click...don't check or don't see.


De rov he also hack my computer and phone after second reward i get. All my
pass and detail.

Before hack at many quest in telagram he help. on the way many quest reqire
to put passwoard for confirm.

I think he see from that. Thay why help me a lot for do the qeust.

That why can take my reward direct from the comunity solscan tron +
