### ISSUE TITLE
Error building tdweb (openssl)

### ISSUE THREAD

**Issue by andrewmed** [tdlib/td#3042]
Hello. 
I have problem building tdweb on debian 12, arm

```
EMSDK=/home/parallels/code/emsdk
EMSDK_NODE=/home/parallels/code/emsdk/node/18.20.3_64bit/bin/node
HOME=/home/parallels
PATH=/home/parallels/code/emsdk/upstream/emscripten:/home/parallels/code/emsdk/node/18.20.3_64bit/bin:/home/parallels/code/emsdk:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PWD=/home/parallels/code/td/example/web
```

```
> webpack --mode production

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/parallels/code/td/example/web/tdweb/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/parallels/code/td/example/web/tdweb/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/parallels/code/td/example/web/tdweb/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/parallels/code/td/example/web/tdweb/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/parallels/code/td/example/web/tdweb/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/parallels/code/td/example/web/tdweb/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/parallels/code/td/example/web/tdweb/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/parallels/code/td/example/web/tdweb/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/parallels/code/td/example/web/tdweb/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/parallels/code/td/example/web/tdweb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/parallels/code/td/example/web/tdweb/node_modules/babel-loader/lib/index.js:51:71
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.20.3
```

Looks like openssl error.

I using build scripts from web directory. When I was building tdlib I noticed this warn in the logs, but do not know how to fix it:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    OPENSSL_ROOT_DIR
    OPENSSL_SSL_LIBRARY
    OPENSSL_VERSION
```

**Comment by levlam** [comment]
The error isn't relater to tdweb or TDLib.
See https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported.

**Comment by levlam** [comment]
> but got hard fail like

I see no errors in the provided build logs.
