### ISSUE TITLE
GLIBC 2.38 on Ubuntu 22 and less

### ISSUE THREAD

**Issue by feelgood4** [tdlib/td#3149]
I built tdlib binaries with [build instructions](https://tdlib.github.io/td/build.html?language=Java) for Ubuntu 22. It works fine for Ubuntu 24.

But when I build for instruction Ubuntu 22 with two options (g++/clang) any result binary after run java programm print that lib requires GLIBC 2.38 (glibc 2.38 not found).

Is it expected? Ubuntu 22 contains only GLIBC 2.35. Should I locally build GLIBC with excepted version?

**Comment by levlam** [comment]
Binaries aren't portable. You have to build them on Ubuntu 22 to guarantee that they work there. They can't require glibc 2.38 if build using the build instructions on the system that has only glibc 2.35.

**Comment by feelgood4** [comment]
I tried again. I build new libtdjni.so with instruction for Ubuntu 22 with g++. I build it on Ubuntu 22.04 jammie machine. And call new .so in `System.load(`.so file`)` in java application print error:

```
java.lang.UnsatisfiedLinkError: /home/administrator/tgclinet/sample-linux/libtdjni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /home/administrator/tgclinet/sample-linux/libtdjni.so)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
```

For me it's a bit curious because i waited result as you said by default. But it's not
