### ISSUE TITLE
json validation error from ffi napi

### ISSUE THREAD

**Issue by mob2005** [tdlib/td#506]
when i login in a number it's return json validation error and app crash , error is some thing like below :

```

!!e SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at _tdlib.td_json_client_receive.async (/tdlib/node_modules/tdl/dist/tdlib-ffi.js:80:24)
    at Object.<anonymous> (tdlib/node_modules/ffi-napi/lib/_foreign_function.js:115:9)
```

**Comment by levlam** [comment]
td_json_client_receive can return NULL if the timeout expired first. Is it the case?
