### ISSUE TITLE
Unable to use Java pre built library for Android

### ISSUE THREAD

**Issue by mghatiya** [tdlib/td#796]
Hi,

I am trying to use Telegram APIs in my application to login user to Telegram and then make some API calls. Documentation seems to suggest that we need to use TDLib for that.

There are examples for using TDLib in Java and also there is a prebuilt library too for Android.
Unfortunately, for people like me who are not very familiar with these, it is not clear how to use these examples and libraries. They have tons of code written into them, and it is not easy to figure out which part of code is the one that is doing actual integration.

Was not sure how to include the pre built library, as there was no instruction for it on https://github.com/tdlib/td/blob/master/example/README.md#java . So, I have gone ahead with my guesswork.

So, I just unzipped what was at [prebuilt library for Android](https://core.telegram.org/tdlib/tdlib.zip) and copied the "src/main/java/org" folder and everything below it to my app's "java" folder. I suspect other files and folders in this unzipped library also must be of use, but unfortunately because of me being new to Android programming, I had no idea how to utilise it.

And then I added following import lines in my code.

```
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.Client
```

Then I added code from Java Example to my application from [example/java](https://github.com/tdlib/td/tree/master/example/java)

Now with all this it is compiling the code. However, when I am running it, I am getting following error:
```
"No implementation found for org.drinkless.td.libcore.telegram.TdApi$Object org.drinkless.td.libcore.telegram.NativeClient.clientExecute(org.drinkless.td.libcore.telegram.TdApi$Object)" 
```

Documentation on  example/java says following:
```
"If you get java.lang.UnsatisfiedLinkError with "Can't find dependent libraries", you may also need to copy some dependent shared OpenSSL and zlib libraries to bin/."
```

Which are these "some dependent libraries"? Where do I get them? Also, is this message applicable to the error that I am getting? What I am getting is slightly different (I am getting "UnsatisfiedLinkError" but with "No implementation found" and not saying "Can't find dependent libraries".)

I now unzipped the pre-built library in another folder called 'prebuilt-libtd' and tried including jar file to dependencies, by including "gradle/wrapper/gradle-wrapper.jar"by adding following line:
```
implementation fileTree(dir: '/Users/mghatiya/AndroidStudioProjects/prebuilt-libtd/gradle/wrapper', include: ['*.aar', '*.jar'], exclude: [])
```

Not sure if this is the jar file that was intended. I couldn't see any other jar file in the pre built library.
However, the same error continues. I am clueless at the moment as to what else can I try.

Please guide where am I going wrong.

Thanks for the help.

Thanks,
Mukesh

**Comment by levlam** [comment]
You need only add prebuilt library from "src/main/libs/" and binding files from "src/main/java/" to your project. It seems that you done everything right except you didn't add prebuilt library to the project. To add prebuilt shared libraries copy them to the project and follow instructions from https://developer.android.com/studio/projects/gradle-external-native-builds#jniLibs or https://stackoverflow.com/questions/9870435/how-to-link-a-prebuilt-shared-library-to-an-android-ndk-project.

Then the actual integration is done by following lines from NativeClient.java.
```
    static {
        try {
            System.loadLibrary("tdjni");
            Log.w("DLTD", "TDJNI loaded");
        } catch (UnsatisfiedLinkError e) {
            Log.w("DLTD", "Can't find tdjni", e);
        }
    }
```
which load the shared library on application launch.

**Comment by mghatiya** [comment]
Thanks for the answer.

So, I did following:

1. Keep the "org" folder in my "java" folder as is.
2. Remove ``` implementation fileTree(dir: '/Users/.....``` line
3. Add following code to my module's build.gradle in "android" block.
```
    sourceSets {
        main {
            jniLibs.srcDirs 'prebuilt-libtd/src/main/libs'
        }
    }
    defaultConfig {
        ndk {
            abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
        }
    }
```
I was getting following errors while running the code:
```
W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dash.myst-EE6hplBa1lb8y8HLkifIwg==/base.apk"],nativeLibraryDirectories=[/data/app/com.dash.myst-EE6hplBa1lb8y8HLkifIwg==/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libtdjni.so"
W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.dash.myst.TelegramLogin.onCreate(TelegramLogin.kt:84)
```
And
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dash.myst, PID: 14650
    java.lang.UnsatisfiedLinkError: No implementation found for org.drinkless.td.libcore.telegram.TdApi$Object org.drinkless.td.libcore.telegram.NativeClient.clientExecute(org.drinkless.td.libcore.telegram.TdApi$Object) (tried Java_org_drinkless_td_libcore_telegram_NativeClient_clientExecute and Java_org_drinkless_td_libcore_telegram_NativeClient_clientExecute__Lorg_drinkless_td_libcore_telegram_TdApi_00024Object_2)
        at org.drinkless.td.libcore.telegram.NativeClient.clientExecute(Native Method)
        at org.drinkless.td.libcore.telegram.Client.execute(Client.java:119)
        at com.dash.myst.TelegramLogin.onCreate(TelegramLogin.kt:92)
```

Then I copied the content of prebuilt library's "libs" folder to my app's libs folder and changed the gradle file's ```sourceSets``` line to this:
```
jniLibs.srcDirs 'libs'
```

And it seems to be working as of now. Did I do it in the right way?

I am getting some other errors, which I probably should research a bit on and open another thread if required, but at least the library seems to be getting connected.

Thanks,
Mukesh

**Comment by mghatiya** [comment]
Also, since I have integrated the library in this way, whenever library gets updated in future, I have to keep copying the library again? How can I avoid that?

**Comment by levlam** [comment]
@mghatiya Yes, you will need to replace all *.java and *,so files with new one. You can write a script to automate this.

**Comment by mghatiya** [comment]
Thanks Aliaksei for all the help.

**Comment by rishabhhgupta** [comment]
Any one here

**Comment by rishabhhgupta** [comment]
So I'm uploading video using tdlib in my android app, but I didn't get any error and video is not upload in the telegram either, 
here is my code 

`TdApi.InputFile file = new TdApi.InputFileLocal(getPathFromUri(uri));

                                TdApi.InputMessageVideo messageContent = new TdApi.InputMessageVideo(file,null,
                                        null,timeInSec,Integer.parseInt(width),Integer.parseInt(height),
                                        false,null,0);

                                // initialize reply markup just for testing
                                TdApi.InlineKeyboardButton[] row = {new TdApi.InlineKeyboardButton("https://telegram.org?1",
                                        new TdApi.InlineKeyboardButtonTypeUrl()), new TdApi.InlineKeyboardButton("https://telegram.org?2",
                                        new TdApi.InlineKeyboardButtonTypeUrl()), new TdApi.InlineKeyboardButton("https://telegram.org?3",
                                                new TdApi.InlineKeyboardButtonTypeUrl())};
                                TdApi.ReplyMarkup replyMarkup = new TdApi.ReplyMarkupInlineKeyboard(new TdApi.InlineKeyboardButton[][]{row, row, row});

                                client.send(new TdApi.SendMessage(Long.parseLong(snapshot.child("channelId").getValue().toString()),
                                        0, 0, null, replyMarkup, messageContent), new Client.ResultHandler() {
                                    @Override
                                    public void onResult(TdApi.Object object) throws IllegalAccessException {
                                        Log.i("my name is chin",getFieldNamesAndValues(object,true).toString());
                                    }
                                });


`

In my "addedStickersField" in TdApi.InputMessageVideo class in wrote null, because I didn't about this field and according to the documentation I have to write something in List
![chrome_K3wRHenOiu](https://user-images.githubusercontent.com/66349860/166730094-14131484-60bc-4880-b9e0-5b3a762cabce.png)

Any help, why I'm not able to upload video in telegram




`

**Comment by levlam** [comment]
@rishabhhgupta 
See TDLib logs with verbosity level 2 for exact upload error. It is likely that the file isn't accessible from the given path.

**Comment by rishabhhgupta** [comment]
Thank you for your response, how I get verbosity level 2 log, I just only got Tdlib.object as a ResultHandler

**Comment by levlam** [comment]
You can set up TDLib's log with TdApi.SetLogStream and TdApi.SetLogVerbosityLevel.

**Comment by rishabhhgupta** [comment]
It's new class, how I get attach to the TdApi.InputMessageVideo

**Comment by rishabhhgupta** [comment]
If it's wrong path or I get path from Intent as like 
"/storage/emulated/0/DCIM/runtastic/2022-05-04_21_12_59_759_0.jpg"

Is it right or wrong, in my error log I get 

`Receive wrong response from TDLib:
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err: Message {
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   id = 13631633
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   senderId = MessageSenderChat {
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:     chatId = -1001572460740
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   }
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   chatId = -1001572460740
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   sendingState = MessageSendingStatePending {
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   }
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   schedulingState = null
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   isOutgoing = true
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   isPinned = false
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   canBeEdited = false
2022-05-04 22:51:15.772 13539-13761/com.promiseek.cloudo W/System.err:   canBeForwarded = true
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   canBeSaved = true
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   canBeDeletedOnlyForSelf = false
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   canBeDeletedForAllUsers = true
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   canGetStatistics = false
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   canGetMessageThread = false
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   canGetViewers = false
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   canGetMediaTimestampLinks = false
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   hasTimestampedMedia = true
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   isChannelPost = true
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   containsUnreadMention = false
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   date = 1651684876
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   editDate = 0
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   forwardInfo = null
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:   interactionInfo = MessageInteractionInfo {
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:     viewCount = 1
2022-05-04 22:51:15.773 13539-13761/com.promiseek.cloudo W/System.err:     forwardCount = 0
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:     replyInfo = null
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   }
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   replyInChatId = 0
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   replyToMessageId = 0
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   messageThreadId = 0
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   ttl = 0
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   ttlExpiresIn = 0.000000
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   viaBotUserId = 0
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   authorSignature = ""
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   mediaAlbumId = 0
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   restrictionReason = ""
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:   content = MessagePhoto {
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:     photo = Photo {
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:       hasStickers = false
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:       minithumbnail = null
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:       sizes = vector[1] {
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:         PhotoSize {
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:           type = "i"
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:           photo = File {
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:             id = 646
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:             size = 40298
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:             expectedSize = 40298
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:             local = LocalFile {
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               path = "/storage/emulated/0/DCIM/runtastic/2022-05-04_21_12_59_759_0.jpg"
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               canBeDownloaded = false
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               canBeDeleted = false
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               isDownloadingActive = false
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               isDownloadingCompleted = true
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               downloadOffset = 0
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               downloadedPrefixSize = 40298
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               downloadedSize = 40298
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:             }
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:             remote = RemoteFile {
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               id = ""
2022-05-04 22:51:15.774 13539-13761/com.promiseek.cloudo W/System.err:               uniqueId = ""
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:               isUploadingActive = true
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:               isUploadingCompleted = false
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:               uploadedSize = 0
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:             }
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:           }
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:           width = 378
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:           height = 800
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:           progressiveSizes = vector[0] {
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:           }
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:         }
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:       }
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:     }
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:     caption = FormattedText {
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:       text = ""
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:       entities = vector[0] {
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:       }
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:     }
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:     isSecret = false
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:   }
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err:   replyMarkup = null
2022-05-04 22:51:15.775 13539-13761/com.promiseek.cloudo W/System.err: }`

**Comment by rishabhhgupta** [comment]
May you also explain what is addedStickersField and ttl fieds in TdApi.InputMessagePhoto, In document I didn't understand 
![Inkedchrome_rAv4yZThP6_LI](https://user-images.githubusercontent.com/66349860/166744936-09d063ef-3258-4aea-a079-2d0e775c37a6.jpg)

**Comment by levlam** [comment]
You don't need these fields in 99,99% cases.

**Comment by rishabhhgupta** [comment]
ok got it, can you please tell me how I implement TdApi.SetLogVerbosityLevel, from example.java, i just only got this, but how i get verbos
![chrome_tdzuysPbSt](https://user-images.githubusercontent.com/66349860/166859706-30f71381-bfcc-41cb-91ee-56a2a62f9abd.png)
e

please help me

**Comment by rishabhhgupta** [comment]
In my resultHandler I got error of 
Receive wrong response from TDLib:

please do you have any example of java that implement video or images, so i can understand what I'm missioning, 

I'm using TdApi.InputFileLocal for location  as 
"/storage/emulated/0/DCIM/runtastic/2022-05-04_21_12_59_759_0.jpg"

**Comment by rishabhhgupta** [comment]
I'm able to send text messages but not video and images

**Comment by rishabhhgupta** [comment]
bro where are you!!!!!!!!!!!😟☹😖
