### ISSUE TITLE
failed run in java 

### ISSUE THREAD

**Issue by pishnok** [tdlib/td#87]
Hello friends
I could not launch the project.
 Someone will launch a Java project for me?

**Just Part Authorization** 

Thank you.

**Comment by levlam** [comment]
What have you tried to launch and what errors have been received?

**Comment by pishnok** [comment]
i get this errors
`java.net.SocketException: Socket closed
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:141)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
	at anywheresoftware.b4a.shell.ShellConnector.readControlData(ShellConnector.java:191)
`	at anywheresoftware.b4a.shell.ShellConnector.connect(ShellConnector.java:186)
	at anywheresoftware.b4a.shell.ShellConnector.run(ShellConnector.java:119)
	at java.lang.Thread.run(Thread.java:841)`

I need an example to launch this project

**Comment by levlam** [comment]
Are you sure that you are using TDLib? TDLib don't use Java socket implementation.

**Comment by pishnok** [comment]
Yes 100%
i trying to warp this lib to Basic4anroid

**Comment by levlam** [comment]
This error is definitely not from the TDLib.

**Comment by pishnok** [comment]
first need example source code run this lib :) 
I also had no problem with the previous version
