### ISSUE TITLE
OSError: [WinError 193] %1 не является приложением Win32

### ISSUE THREAD

**Issue by Pegorino82** [tdlib/td#968]
I have comiled tdlib for windows with istructions https://tdlib.github.io/td/build.html?language=Python and when i am trying to run tdjson_example.py i've got
Traceback (most recent call last):
```
  ....
  File ".../td/example/python/tdjson_example.py", line 21, in <module>
    tdjson = CDLL(tdjson_path)
  File "...\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 не является приложением Win32
```

**Comment by levlam** [comment]
Check that you build TDLib for expected x86/x64 architecture. Build instructions for Windows has switch "Choose for which bitness you want to build TDLib".

**Comment by Pegorino82** [comment]
i tried both of them, result is the same

**Comment by levlam** [comment]
You also need to check that all dependent libraries are for the correct architecture, i.e. x64 for 64-bit tdjson.dll and x86 for 32-bit tdjson.dll.

**Comment by Pegorino82** [comment]
ok, i'll try to reinstall all dependencies, thx!

**Comment by Pegorino82** [comment]
when i compile for x86 i get ```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(507
,5): error MSB6006: "CL.exe" завершилась с кодом -529706956. [C:\td\build\tdcore.vcxproj]
``` error in log and there is no tdlib folder created.

**Comment by Pegorino82** [comment]
compiling for x64 shows no errors, but when run  tdjson_example.py - error from first post (

**Comment by levlam** [comment]
You can install Python for x86-64 from https://www.python.org/downloads/windows/ to be able to use 64-bit shared library.

Alternatively, I can tell you what is wrong with the 32-bit build, if you send all cmake invocation and build logs.

**Comment by Pegorino82** [comment]
@levlam thanks a lot for your help, now i think i doing something wrong
`FileNotFoundError: Could not find module 'C:\td\example\python\tdlib\bin\tdjson.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

**Comment by Pegorino82** [comment]
> You can install Python for x86-64 from https://www.python.org/downloads/windows/ to be able to use 64-bit shared library.
> 
> Alternatively, I can tell you what is wrong with the 32-bit build, if you send all cmake invocation and build logs.

now i have build/ for x64 and i fiond there in CMakeFiles CMakeError.log

```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/td/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_5e9a7.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine версии 16.5.0+d4cbfca49 для .NET Framework

(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.



  Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.25.28610.4 для x64

  CheckIncludeFile.c

  (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5e9a7.dir\Debug\\" /Fd"cmTC_5e9a7.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue C:\td\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

C:\td\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: Не удается открыть файл включение: pthread.h: No such file or directory, [C:\td\build\CMakeFiles\CMakeTmp\cmTC_5e9a7.vcxproj]




Performing C++ SOURCE FILE Test COMPILER_HAS_DEPRECATED_ATTR failed with the following output:
Change Dir: C:/td/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_094de.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine версии 16.5.0+d4cbfca49 для .NET Framework

(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.



  Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.25.28610.4 для x64

  src.cxx

  (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.

  cl /c /Zi /W4 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D COMPILER_HAS_DEPRECATED_ATTR /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"cmTC_094de.dir\Debug\\" /Fd"cmTC_094de.dir\Debug\vc142.pdb" /Gd /TP /wd4100 /wd4127 /wd4324 /wd4505 /wd4814 /wd4702 /errorReport:queue  /utf-8 C:\td\build\CMakeFiles\CMakeTmp\src.cxx

C:\td\build\CMakeFiles\CMakeTmp\src.cxx(1,16): error C2065: __deprecated__: необъявленный идентификатор [C:\td\build\CMakeFiles\CMakeTmp\cmTC_094de.vcxproj]

C:\td\build\CMakeFiles\CMakeTmp\src.cxx(1,31): error C4430: отсутствует спецификатор типа - предполагается int. Примечание. C++ не поддерживает int по умолчанию [C:\td\build\CMakeFiles\CMakeTmp\cmTC_094de.vcxproj]

C:\td\build\CMakeFiles\CMakeTmp\src.cxx(1,37): error C2448: __attribute__: вероятно, инициализатор, использующий стиль функции, является определением функции [C:\td\build\CMakeFiles\CMakeTmp\cmTC_094de.vcxproj]



Source file was:
__attribute__((__deprecated__)) int somefunc() { return 0; }
    int main() { return somefunc();}
```

**Comment by levlam** [comment]
The cited part of the log is not an error at all. To identify the problem you need to begin building from scratch in a clean build directory and provide console output of all invocations.

**Comment by Pegorino82** [comment]
> The cited part of the log is not an error at all. To identify the problem you need to begin building from scratch in a clean build directory and provide console output of all invocations.

ok, here is it

```
PS C:\td> cd .\build\
PS C:\td\build> cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- Building for: Visual Studio 16 2019
-- The CXX compiler identification is MSVC 19.25.28610.4
-- The C compiler identification is MSVC 19.25.28610.4
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find ccache (this is NOT an error)
-- Found OpenSSL: C:/td/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib (found version "1.1.1d")
-- Found OpenSSL: C:/td/vcpkg/installed/x64-windows/include C:/td/vcpkg/installed/x64-windows/debug/lib/libssl.lib;C:/td/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found ZLIB: optimized;C:/td/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/td/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11")
-- Found ZLIB: C:/td/vcpkg/installed/x64-windows/include optimized;C:/td/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/td/vcpkg/installed/x64-windows/debug/lib/zlibd.lib
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY)
-- Could NOT find Readline (this is NOT an error)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/td/build
PS C:\td\build> cmake --build . --target install --config Release
Microsoft (R) Build Engine версии 16.5.0+d4cbfca49 для .NET Framework
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Checking Build System
  Generate git_commit.h
  Building Custom Rule C:/td/CMakeLists.txt
  Building Custom Rule C:/td/tdutils/generate/CMakeLists.txt
  generate_mime_types_gperf.cpp
  generate_mime_types_gperf.vcxproj -> C:\td\build\tdutils\generate\Release\generate_mime_types_gperf.exe
  Generating ../../../tdutils/generate/auto/mime_type_to_extension.gperf, ../../../tdutils/generate/auto/extension_to_mime_type.gperf
  Extension "wmz" matches more than one type
  Extension "sub" matches more than one type
  Building Custom Rule C:/td/tdutils/generate/CMakeLists.txt
  Generating ../../../tdutils/generate/auto/mime_type_to_extension.cpp
  Generating ../../../tdutils/generate/auto/extension_to_mime_type.cpp
  Building Custom Rule C:/td/tdutils/CMakeLists.txt
  Clocks.cpp
  FileFd.cpp
  IPAddress.cpp
  MemoryMapping.cpp
  path.cpp
  PollFlags.cpp
  ServerSocketFd.cpp
  signals.cpp
  sleep.cpp
  SocketFd.cpp
  stacktrace.cpp
  Stat.cpp
  StdStreams.cpp
  thread_local.cpp
  UdpSocketFd.cpp
  wstring_convert.cpp
  Epoll.cpp
  EventFdBsd.cpp
  EventFdLinux.cpp
  EventFdWindows.cpp
  Создание кода...
  Компиляция...
  Iocp.cpp
  KQueue.cpp
  NativeFd.cpp
  Poll.cpp
  Select.cpp
  ThreadIdGuard.cpp
  ThreadPthread.cpp
  WineventPoll.cpp
  base64.cpp
  BigNum.cpp
  buffer.cpp
  BufferedUdp.cpp
  check.cpp
  crypto.cpp
  FileLog.cpp
  filesystem.cpp
  find_boundary.cpp
  Gzip.cpp
  GzipByteFlow.cpp
  Hints.cpp
  Создание кода...
  Компиляция...
  HttpUrl.cpp
  JsonBuilder.cpp
  logging.cpp
  misc.cpp
  MimeType.cpp
  MpmcQueue.cpp
  OptionsParser.cpp
  PathView.cpp
  Random.cpp
  SharedSlice.cpp
  Slice.cpp
  StackAllocator.cpp
  Status.cpp
  StringBuilder.cpp
  tests.cpp
  Time.cpp
  Timer.cpp
  tl_parsers.cpp
  translit.cpp
  TsFileLog.cpp
  Создание кода...
  Компиляция...
  unicode.cpp
  utf8.cpp
  Создание кода...
  mime_type_to_extension.cpp
  extension_to_mime_type.cpp
  Создание кода...
  tdutils.vcxproj -> C:\td\build\tdutils\Release\tdutils.lib
  Building Custom Rule C:/td/tdactor/CMakeLists.txt
  ConcurrentScheduler.cpp
  Scheduler.cpp
  MultiPromise.cpp
  Timeout.cpp
  Создание кода...
  tdactor.vcxproj -> C:\td\build\tdactor\Release\tdactor.lib
  Building Custom Rule C:/td/tdtl/CMakeLists.txt
  tl_config.cpp
  tl_core.cpp
  tl_file_outputer.cpp
  tl_file_utils.cpp
  tl_generate.cpp
  tl_outputer.cpp
  tl_string_outputer.cpp
  tl_writer.cpp
  Создание кода...
  tdtl.vcxproj -> C:\td\build\tdtl\Release\tdtl.lib
  Building Custom Rule C:/td/td/generate/CMakeLists.txt
  generate_common.cpp
  tl_writer_cpp.cpp
  tl_writer_h.cpp
  tl_writer_hpp.cpp
  tl_writer_jni_cpp.cpp
  tl_writer_jni_h.cpp
  tl_writer_td.cpp
  Создание кода...
  generate_common.vcxproj -> C:\td\build\td\generate\Release\generate_common.exe
  Generate common tl source files
  Building Custom Rule C:/td/td/generate/CMakeLists.txt
  Building Custom Rule C:/td/sqlite/CMakeLists.txt
  sqlite3.c
  tdsqlite.vcxproj -> C:\td\build\sqlite\Release\tdsqlite.lib
  Building Custom Rule C:/td/tddb/CMakeLists.txt
  Binlog.cpp
  BinlogEvent.cpp
  ConcurrentBinlog.cpp
  BinlogEventsBuffer.cpp
  BinlogEventsProcessor.cpp
  SqliteConnectionSafe.cpp
  SqliteDb.cpp
  SqliteKeyValue.cpp
  SqliteKeyValueAsync.cpp
  SqliteStatement.cpp
  RawSqliteDb.cpp
  Создание кода...
  tddb.vcxproj -> C:\td\build\tddb\Release\tddb.lib
  Building Custom Rule C:/td/tdnet/CMakeLists.txt
  GetHostByNameActor.cpp
  HttpChunkedByteFlow.cpp
  HttpConnectionBase.cpp
  HttpContentLengthByteFlow.cpp
  HttpFile.cpp
  HttpInboundConnection.cpp
  HttpOutboundConnection.cpp
  HttpProxy.cpp
  HttpQuery.cpp
  HttpReader.cpp
  Socks5.cpp
  SslStream.cpp
  TcpListener.cpp
  TransparentProxy.cpp
  Wget.cpp
  Создание кода...
  tdnet.vcxproj -> C:\td\build\tdnet\Release\tdnet.lib
  Building Custom Rule C:/td/CMakeLists.txt
  AuthData.cpp
  crypto.cpp
  DhHandshake.cpp
  Handshake.cpp
  HandshakeActor.cpp
  HttpTransport.cpp
  IStreamTransport.cpp
  KDF.cpp
  Ping.cpp
  PingConnection.cpp
  ProxySecret.cpp
  RawConnection.cpp
  SessionConnection.cpp
  TcpTransport.cpp
  TlsInit.cpp
  TlsReaderByteFlow.cpp
  Transport.cpp
  utils.cpp
  AnimationsManager.cpp
  AudiosManager.cpp
  Создание кода...
  Компиляция...
  AuthManager.cpp
  AutoDownloadSettings.cpp
  BackgroundManager.cpp
  BackgroundType.cpp
  CallActor.cpp
  CallDiscardReason.cpp
  CallManager.cpp
  CallbackQueriesManager.cpp
  ClientActor.cpp
  ConfigManager.cpp
  ConfigShared.cpp
  Contact.cpp
  ContactsManager.cpp
  DelayDispatcher.cpp
  Dependencies.cpp
  DeviceTokenManager.cpp
  DhCache.cpp
  DialogAdministrator.cpp
  DialogDb.cpp
  DialogId.cpp
  Создание кода...
  Компиляция...
  DialogLocation.cpp
  DialogParticipant.cpp
  Document.cpp
  DocumentsManager.cpp
  DraftMessage.cpp
  FileReferenceManager.cpp
  FileBitmask.cpp
  FileDb.cpp
  FileDownloader.cpp
  FileEncryptionKey.cpp
  FileFromBytes.cpp
  FileGcParameters.cpp
  FileGcWorker.cpp
  FileGenerateManager.cpp
  FileHashUploader.cpp
  FileLoader.cpp
  FileLoaderUtils.cpp
  FileLoadManager.cpp
  FileManager.cpp
  FileStats.cpp
  Создание кода...
  Компиляция...
  FileStatsWorker.cpp
  FileUploader.cpp
  PartsManager.cpp
  ResourceManager.cpp
  Game.cpp
  Global.cpp
  HashtagHints.cpp
  InlineQueriesManager.cpp
  InputMessageText.cpp
  JsonValue.cpp
  LanguagePackManager.cpp
  Location.cpp
  Logging.cpp
  MessageContent.cpp
  MessageContentType.cpp
  MessageEntity.cpp
  MessageId.cpp
  MessagesDb.cpp
  MessagesManager.cpp
  misc.cpp
  Создание кода...
  Компиляция...
  AuthDataShared.cpp
  ConnectionCreator.cpp
  DcAuthManager.cpp
  DcOptionsSet.cpp
  MtprotoHeader.cpp
  NetActor.cpp
  NetQuery.cpp
  NetQueryCounter.cpp
  NetQueryCreator.cpp
  NetQueryDelayer.cpp
  NetQueryDispatcher.cpp
  NetStatsManager.cpp
  Proxy.cpp
  PublicRsaKeyShared.cpp
  PublicRsaKeyWatchdog.cpp
  Session.cpp
  SessionProxy.cpp
  SessionMultiProxy.cpp
  NotificationManager.cpp
  NotificationSettings.cpp
  Создание кода...
  Компиляция...
  NotificationType.cpp
  Payments.cpp
  PasswordManager.cpp
  PhoneNumberManager.cpp
  PrivacyManager.cpp
  Photo.cpp
  PhotoSizeSource.cpp
  PollManager.cpp
  QueryCombiner.cpp
  ReplyMarkup.cpp
  RestrictionReason.cpp
  SecretChatActor.cpp
  SecretChatDb.cpp
  SecretChatsManager.cpp
  SecureManager.cpp
  SecureStorage.cpp
  SecureValue.cpp
  SendCodeHelper.cpp
  SequenceDispatcher.cpp
  StateManager.cpp
  Создание кода...
  Компиляция...
  StickersManager.cpp
  StorageManager.cpp
  Td.cpp
  TdDb.cpp
  TermsOfService.cpp
  TopDialogManager.cpp
  UpdatesManager.cpp
  Venue.cpp
  VideoNotesManager.cpp
  VideosManager.cpp
  VoiceNotesManager.cpp
  WebPageBlock.cpp
  WebPagesManager.cpp
  mtproto_api.cpp
  td_api.cpp
  telegram_api.cpp
  secret_api.cpp
  Создание кода...
  tdcore.vcxproj -> C:\td\build\Release\tdcore.lib
  Building Custom Rule C:/td/CMakeLists.txt
  Client.cpp
  Log.cpp
  Создание кода...
  tdclient.vcxproj -> C:\td\build\Release\tdclient.lib
  Building Custom Rule C:/td/test/CMakeLists.txt
  db.cpp
  http.cpp
  mtproto.cpp
  message_entities.cpp
  poll.cpp
  secret.cpp
  secure_storage.cpp
  set_with_position.cpp
  string_cleaning.cpp
  tdclient.cpp
  data.cpp
  buffer.cpp
  ConcurrentHashMap.cpp
  crypto.cpp
  Enumerator.cpp
  EpochBasedMemoryReclamation.cpp
  filesystem.cpp
  gzip.cpp
  HazardPointers.cpp
  heap.cpp
  Создание кода...
  Компиляция...
  json.cpp
  log.cpp
  misc.cpp
  MpmcQueue.cpp
  MpmcWaiter.cpp
  MpscLinkQueue.cpp
  OrderedEventsProcessor.cpp
  port.cpp
  pq.cpp
  SharedObjectPool.cpp
  SharedSlice.cpp
  variant.cpp
  actors_main.cpp
  actors_simple.cpp
  actors_workers.cpp
  actors_bugs.cpp
  Создание кода...
  all_tests.vcxproj -> C:\td\build\test\Release\all_tests.lib
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_actor.cpp
  bench_actor.vcxproj -> C:\td\build\benchmark\Release\bench_actor.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_crypto.cpp
  bench_crypto.vcxproj -> C:\td\build\benchmark\Release\bench_crypto.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_db.cpp
  bench_db.vcxproj -> C:\td\build\benchmark\Release\bench_db.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_empty.cpp
  bench_empty.vcxproj -> C:\td\build\benchmark\Release\bench_empty.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_handshake.cpp
  bench_handshake.vcxproj -> C:\td\build\benchmark\Release\bench_handshake.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_http.cpp
  bench_http.vcxproj -> C:\td\build\benchmark\Release\bench_http.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_http_reader.cpp
  bench_http_reader.vcxproj -> C:\td\build\benchmark\Release\bench_http_reader.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_http_server.cpp
  bench_http_server.vcxproj -> C:\td\build\benchmark\Release\bench_http_server.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_http_server_cheat.cpp
  bench_http_server_cheat.vcxproj -> C:\td\build\benchmark\Release\bench_http_server_cheat.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_http_server_fast.cpp
  bench_http_server_fast.vcxproj -> C:\td\build\benchmark\Release\bench_http_server_fast.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_misc.cpp
  bench_misc.vcxproj -> C:\td\build\benchmark\Release\bench_misc.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  bench_tddb.cpp
  bench_tddb.vcxproj -> C:\td\build\benchmark\Release\bench_tddb.exe
  Building Custom Rule C:/td/tddb/CMakeLists.txt
  binlog_dump.cpp
  binlog_dump.vcxproj -> C:\td\build\tddb\Release\binlog_dump.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  check_proxy.cpp
  check_proxy.vcxproj -> C:\td\build\benchmark\Release\check_proxy.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  check_tls.cpp
  check_tls.vcxproj -> C:\td\build\benchmark\Release\check_tls.exe
  Building Custom Rule C:/td/tdactor/CMakeLists.txt
  example.cpp
  example.vcxproj -> C:\td\build\tdactor\Release\example.exe
  Building Custom Rule C:/td/td/generate/CMakeLists.txt
  generate_c.cpp
  generate_c.vcxproj -> C:\td\build\td\generate\Release\generate_c.exe
  Building Custom Rule C:/td/td/generate/CMakeLists.txt
  generate_json.cpp
  tl_json_converter.cpp
  Создание кода...
  generate_json.vcxproj -> C:\td\build\td\generate\Release\generate_json.exe
  Building Custom Rule C:/td/CMakeLists.txt
  memprof.cpp
  memprof.vcxproj -> C:\td\build\Release\memprof.lib
  Building Custom Rule C:/td/td/generate/CMakeLists.txt
  remove_documentation.cpp
  remove_documentation.vcxproj -> C:\td\build\td\generate\Release\remove_documentation.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  rmdir.cpp
  rmdir.vcxproj -> C:\td\build\benchmark\Release\rmdir.exe
  Building Custom Rule C:/td/test/CMakeLists.txt
  main.cpp
  db.cpp
  http.cpp
  mtproto.cpp
  message_entities.cpp
  poll.cpp
  secret.cpp
  secure_storage.cpp
  set_with_position.cpp
  string_cleaning.cpp
  tdclient.cpp
  data.cpp
  buffer.cpp
  ConcurrentHashMap.cpp
  crypto.cpp
  Enumerator.cpp
  EpochBasedMemoryReclamation.cpp
  filesystem.cpp
  gzip.cpp
  HazardPointers.cpp
  Создание кода...
  Компиляция...
  heap.cpp
  json.cpp
  log.cpp
  misc.cpp
  MpmcQueue.cpp
  MpmcWaiter.cpp
  MpscLinkQueue.cpp
  OrderedEventsProcessor.cpp
  port.cpp
  pq.cpp
  SharedObjectPool.cpp
  SharedSlice.cpp
  variant.cpp
  actors_main.cpp
  actors_simple.cpp
  actors_workers.cpp
  actors_bugs.cpp
  Создание кода...
  run_all_tests.vcxproj -> C:\td\build\test\Release\run_all_tests.exe
  Building Custom Rule C:/td/td/generate/CMakeLists.txt
  generate_java.cpp
  tl_writer_java.cpp
  Создание кода...
  td_generate_java_api.vcxproj -> C:\td\build\td\generate\Release\td_generate_java_api.exe
  Generate JSON tl source files
  Building Custom Rule C:/td/td/generate/CMakeLists.txt
  Building Custom Rule C:/td/CMakeLists.txt
  td_api_json.cpp
  ClientJson.cpp
  Создание кода...
  tdjson_private.vcxproj -> C:\td\build\Release\tdjson_private.lib
  Building Custom Rule C:/td/CMakeLists.txt
  td_json_client.cpp
  td_log.cpp
  Создание кода...
     Создается библиотека C:/td/build/Release/tdjson.lib и объект C:/td/build/Release/tdjson.exp
  tdjson.vcxproj -> C:\td\build\Release\tdjson.dll
  Building Custom Rule C:/td/CMakeLists.txt
  td_json_client.cpp
  td_log.cpp
  Создание кода...
  tdjson_static.vcxproj -> C:\td\build\Release\tdjson_static.lib
  Building Custom Rule C:/td/CMakeLists.txt
  cli.cpp
  td_api_json.cpp
  Создание кода...
  tg_cli.vcxproj -> C:\td\build\Release\tg_cli.exe
  Building Custom Rule C:/td/benchmark/CMakeLists.txt
  wget.cpp
  wget.vcxproj -> C:\td\build\benchmark\Release\wget.exe
  Building Custom Rule C:/td/CMakeLists.txt
  -- Install configuration: "Release"
  -- Installing: C:/td/build/../tdlib/lib/tdjson.lib
  -- Installing: C:/td/build/../tdlib/bin/tdjson.dll
  -- Installing: C:/td/build/../tdlib/lib/tdjson_static.lib
  -- Installing: C:/td/build/../tdlib/lib/tdjson_private.lib
  -- Installing: C:/td/build/../tdlib/lib/tdclient.lib
  -- Installing: C:/td/build/../tdlib/lib/tdcore.lib
  -- Installing: C:/td/build/../tdlib/lib/cmake/Td/TdTargets.cmake
  -- Installing: C:/td/build/../tdlib/lib/cmake/Td/TdTargets-release.cmake
  -- Installing: C:/td/build/../tdlib/include/td/telegram/td_json_client.h
  -- Installing: C:/td/build/../tdlib/include/td/telegram/td_log.h
  -- Installing: C:/td/build/../tdlib/include/td/telegram/tdjson_export.h
  -- Installing: C:/td/build/../tdlib/include/td/telegram/Client.h
  -- Installing: C:/td/build/../tdlib/include/td/telegram/Log.h
  -- Installing: C:/td/build/../tdlib/include/td/tl/TlObject.h
  -- Installing: C:/td/build/../tdlib/include/td/telegram/td_api.h
  -- Installing: C:/td/build/../tdlib/include/td/telegram/td_api.hpp
  -- Installing: C:/td/build/../tdlib/lib/cmake/Td/TdConfig.cmake
  -- Installing: C:/td/build/../tdlib/lib/cmake/Td/TdConfigVersion.cmake
  -- Installing: C:/td/build/../tdlib/lib/tdutils.lib
  -- Installing: C:/td/build/../tdlib/lib/tdactor.lib
  -- Installing: C:/td/build/../tdlib/lib/tdnet.lib
  -- Installing: C:/td/build/../tdlib/lib/tdsqlite.lib
  -- Installing: C:/td/build/../tdlib/lib/tddb.lib
PS C:\td\build>
```

**Comment by levlam** [comment]
This is a log of successful 64-bit build. `C:/td/tdlib/bin/tdjson.dll` will work with x86-64 Python.

**Comment by Pegorino82** [comment]
yes, i've got this, but while running example i have error

`FileNotFoundError: Could not find module 'C:\td\tdlib\bin\tdjson.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

i tried to open with full path to this directory, and i tried to copy dll into example dir - result is the same

**Comment by Pegorino82** [comment]
for different python interpretators different errors

```
python:      3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
tdjson_path: C:/td/tdlib/bin/tdjson.dll
Traceback (most recent call last):
  File "C:/td/example/python/tdjson_example.py", line 23, in <module>
    tdjson = CDLL(tdjson_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 не является приложением Win32
```

```
python:      3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
tdjson_path: C:/td/tdlib/bin/tdjson.dll
Traceback (most recent call last):
  File "C:/td/example/python/tdjson_example.py", line 23, in <module>
    tdjson = CDLL(tdjson_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\td\tdlib\bin\tdjson.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by levlam** [comment]
The key part is `(or one of its dependencies)` now. You need to copy zlib and OpenSSL libraries, i.e. `C:/td/vcpkg/installed/x64-windows/bin/*.dll`, to the directory from which the Python script is run. `tdjson.dll` also can be copied to the directory, so you can use relative path.

**Comment by Pegorino82** [comment]
> The key part is `(or one of its dependencies)` now. You need to copy zlib and OpenSSL libraries, i.e. `C:/td/vcpkg/installed/x64-windows/bin/*.dll`, to the directory from which the Python script is run. `tdjson.dll` also can be copied to the directory, so you can use relative path.

yes! this works, thanks a lot!
